"""added psysuite apk management

Revision ID: 1322ec780acd
Revises: 8ee4d82ef1a1
Create Date: 2020-07-30 16:27:14.595064

"""

# revision identifiers, used by Alembic.
revision = '1322ec780acd'
down_revision = '8ee4d82ef1a1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psysuite_mobile_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sver', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('apk_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psysuite_mobile_application')
    ### end Alembic commands ###
