"""can delete session, removed foreignkey in error.session_uid

Revision ID: 15ffd1fb75a5
Revises: 353ff9a42df3
Create Date: 2018-07-10 15:49:08.594627

"""

# revision identifiers, used by Alembic.
revision = '15ffd1fb75a5'
down_revision = '353ff9a42df3'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('error_session_uid_fkey', 'error', type_='foreignkey')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key('error_session_uid_fkey', 'error', 'training_session', ['session_uid'], ['session_uid'])
    ### end Alembic commands ###
