"""psysuite added

Revision ID: b46140ca0be4
Revises: None
Create Date: 2020-07-31 04:00:06.830491

"""

# revision identifiers, used by Alembic.
revision = 'b46140ca0be4'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('psysuite_mobile_application',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('sver', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('apk_path', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('version')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('psysuite_mobile_application')
    ### end Alembic commands ###
